# Generated by Django 3.2.4 on 2021-07-21 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resevation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='date',
        ),
    ]
