export const ActionTypes = {
    SET_PRODUCTS : "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED",


    SET_SHOPS : "SET_SHOPS",
    SELECTED_SHOP: "SELECTED_SHOP",
    REMOVE_SELECTED_SHOP: "REMOVE_SELECTED_SHOP",

};