export const ActionTypes = {
    SET_PRODUCTS : "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED",

    ADD_PRODUCT: 'ADD_PRODUCT',



    SET_SHOPS : "SET_SHOPS",
    SELECTED_SHOP: "SELECTED_SHOP",
    REMOVE_SELECTED_SHOP: "REMOVE_SELECTED_SHOP",

    ADD_SHOP: 'ADD_SHOP',

    SET_USERS : "SET_USERS",
    SELECTED_USER: "SELECTED_USER",
    REMOVE_SELECTED_USER: "REMOVE_SELECTED_USER",

    SET_REVIEWS : "SET_REVIEWS",
    SELECTED_REVIEW: "SELECTED_REVIEW",
    REMOVE_SELECTED_REVIEW: "REMOVE_SELECTED_REVIEW",
    ADD_REVIEW: 'ADD_REVIEW',


};