# Generated by Django 3.2.4 on 2021-07-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teespring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='orders',
            field=models.ManyToManyField(to='teespring.Order', verbose_name='Orders of user'),
        ),
    ]
