# Generated by Django 3.2.4 on 2021-06-04 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teespring', '0004_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
