# Generated by Django 3.2.4 on 2021-06-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teespring', '0006_auto_20210604_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='URL'),
        ),
    ]
