# Generated by Django 3.2.4 on 2021-06-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teespring', '0008_auto_20210606_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Draft'),
        ),
    ]
