# Generated by Django 3.2.4 on 2021-06-08 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teespring', '0009_alter_product_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_on_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teespring.store', verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
