# Generated by Django 3.2.4 on 2021-06-22 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teespring', '0012_auto_20210612_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
    ]
