# Generated by Django 3.2.4 on 2021-06-22 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teespring', '0014_productstorerelation_userproductrelation_userstorerelation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductStoreRelation',
        ),
        migrations.AddField(
            model_name='product',
            name='customers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
