# Generated by Django 3.2.4 on 2021-06-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teespring', '0015_auto_20210625_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buying_type',
            field=models.CharField(choices=[('Self delivery', 'Delivery self'), ('Delivery', 'Delivery')], default='Self delivery', max_length=100, verbose_name='Type order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New order'), ('In_progress', 'The order is being processed'), ('Is_ready', 'Order is ready'), ('Completed', 'The order is completed')], default='New', max_length=100, verbose_name='Status order'),
        ),
    ]
