export const CREATE_PRODUCT = 'PRODUCT/CREATE_PRODUCT'
export const FETCH_PRODUCTS = 'PRODUCT/FETCH_PRODUCTS'

export const SHOW_LOADER = 'APP/SHOW_LOADER'
export const HIDE_LOADER = 'APP/HIDE_LOADER'